

LIB = libmatrix.a
FILES   =   alloc demo jacobi norm qr system choleski inverse jordan operator quatern unary construc io lu points rotation vector creat is manip ql svdcmp 	
include ../makefile

